---
Name: guysartorelli-composable-validators-config
---
# Add styling to CMS
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - 'guysartorelli/silverstripe-composable-validators:client/dist/left-and-main.css'
