name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    name: CI
    uses: silverstripe/gha-ci/.github/workflows/ci.yml@v1
    with:
      extra_jobs: |
        - php: 8.0
          phpunit: false
          endtoend: true
          endtoend_suite: admin
          endtoend_config: vendor/silverstripe/admin/behat.yml
        - php: 8.1
          phpunit: false
          endtoend: true
          endtoend_suite: cms
          endtoend_config: vendor/silverstripe/cms/behat.yml
